In [1]:
import tensorflow as tf

In [2]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [4]:
W1 = tf.Variable(tf.random_normal([1]), name='weight1')
W2 = tf.Variable(tf.random_normal([1]), name='weight1')
W3 = tf.Variable(tf.random_normal([1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='weight1')
hypothisis = x1 * W1 + x2 * W2 + x3 * W3 +b  

In [5]:
cost = tf.reduce_mean(tf.square(hypothisis-Y))
optimizer  = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothisis, train],
                                  feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 ==0:
        print(step, 'cost: ', cost_val, '\nprediction:\n', hy_val)

0 cost:  6791.1523 
prediction:
 [ 80.205185  95.257416  94.38493  105.191895  70.08698 ]
10 cost:  8.460975 
prediction:
 [153.05115 182.82922 180.66248 199.14609 136.8862 ]
20 cost:  8.368649 
prediction:
 [153.26299 183.10017 180.921   199.42775 137.09683]
30 cost:  8.338545 
prediction:
 [153.25507 183.10695 180.91927 199.42598 137.10597]
40 cost:  8.308657 
prediction:
 [153.24649 183.11288 180.91673 199.42334 137.11444]
50 cost:  8.278845 
prediction:
 [153.23796 183.11882 180.91422 199.4207  137.12292]
60 cost:  8.249252 
prediction:
 [153.22943 183.12476 180.91173 199.41809 137.13136]
70 cost:  8.2197895 
prediction:
 [153.22093 183.13065 180.90923 199.41547 137.13979]
80 cost:  8.190463 
prediction:
 [153.21246 183.13654 180.90674 199.41287 137.14821]
90 cost:  8.1613 
prediction:
 [153.20403 183.14241 180.90425 199.41028 137.1566 ]
100 cost:  8.132301 
prediction:
 [153.19562 183.14827 180.90178 199.40768 137.16496]
110 cost:  8.10342 
prediction:
 [153.18721 183.15411 180.89

990 cost:  6.0665627 
prediction:
 [152.53384 183.6091  180.70811 199.19673 137.82954]
1000 cost:  6.0482664 
prediction:
 [152.52731 183.61363 180.7062  199.19455 137.83618]
1010 cost:  6.030051 
prediction:
 [152.5208  183.6182  180.70433 199.1924  137.84282]
1020 cost:  6.011951 
prediction:
 [152.51431 183.62273 180.70244 199.19025 137.84943]
1030 cost:  5.993943 
prediction:
 [152.50784 183.62723 180.70053 199.18808 137.856  ]
1040 cost:  5.976018 
prediction:
 [152.50139 183.63176 180.69868 199.18596 137.8626 ]
1050 cost:  5.9581923 
prediction:
 [152.49495 183.63623 180.6968  199.18382 137.86916]
1060 cost:  5.9404535 
prediction:
 [152.48854 183.64072 180.69495 199.18167 137.87569]
1070 cost:  5.9228044 
prediction:
 [152.48215 183.64519 180.69308 199.17955 137.88222]
1080 cost:  5.9052477 
prediction:
 [152.47575 183.64963 180.69122 199.17741 137.88872]
1090 cost:  5.8877826 
prediction:
 [152.4694  183.65408 180.68939 199.17531 137.89522]
1100 cost:  5.8703814 
prediction:
 [

----------------------------------------------------------

In [8]:
x_data = [[73.,80.,75.,],[93.,88.,93.],[88.,91.,80.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.,],[185.],[180.],[196,],[142.]]

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]), name='weight')
b=tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
hypothisis = tf.matmul(X,W) +b

In [10]:
cost = tf.reduce_mean(tf.square(hypothisis -Y)) 

In [11]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [13]:
for step in range(2001):
    cost_val, hy_val,_ = sess.run(
    [cost, hypothisis, train], feed_dict={X:x_data,Y:y_data,})
    if step % 10 ==0:
        print(step, 'cost', cost_val, '\nprediction\n', hy_val)

0 cost 47.952087 
prediction
 [[160.61649]
 [178.98291]
 [189.82864]
 [196.27133]
 [136.28726]]
10 cost 45.717533 
prediction
 [[159.3672 ]
 [177.538  ]
 [188.40068]
 [194.69847]
 [135.19081]]
20 cost 45.370552 
prediction
 [[159.3388 ]
 [177.55989]
 [188.35994]
 [194.69954]
 [135.21327]]
30 cost 45.026512 
prediction
 [[159.31474]
 [177.58673]
 [188.32414]
 [194.706  ]
 [135.23947]]
40 cost 44.684887 
prediction
 [[159.29077]
 [177.6135 ]
 [188.28848]
 [194.7125 ]
 [135.26561]]
50 cost 44.34593 
prediction
 [[159.26688]
 [177.64017]
 [188.25299]
 [194.71895]
 [135.29164]]
60 cost 44.009575 
prediction
 [[159.24309]
 [177.66675]
 [188.21764]
 [194.72536]
 [135.31758]]
70 cost 43.67583 
prediction
 [[159.2194 ]
 [177.69322]
 [188.18242]
 [194.73177]
 [135.34343]]
80 cost 43.34456 
prediction
 [[159.19577]
 [177.71956]
 [188.14728]
 [194.73808]
 [135.36914]]
90 cost 43.01604 
prediction
 [[159.17227]
 [177.74583]
 [188.11238]
 [194.74442]
 [135.3948 ]]
100 cost 42.689728 
prediction
 [[1

880 cost 23.633059 
prediction
 [[157.56339]
 [179.53214]
 [185.75024]
 [195.16348]
 [137.14702]]
890 cost 23.455372 
prediction
 [[157.54588]
 [179.55145]
 [185.72487]
 [195.16788]
 [137.16608]]
900 cost 23.279 
prediction
 [[157.52843]
 [179.57071]
 [185.6996 ]
 [195.17224]
 [137.18506]]
910 cost 23.104132 
prediction
 [[157.51106]
 [179.58987]
 [185.67445]
 [195.17659]
 [137.20396]]
920 cost 22.930496 
prediction
 [[157.49374]
 [179.60896]
 [185.64937]
 [195.18091]
 [137.2228 ]]
930 cost 22.758121 
prediction
 [[157.47647]
 [179.62802]
 [185.62442]
 [195.18521]
 [137.24156]]
940 cost 22.58713 
prediction
 [[157.45929]
 [179.64697]
 [185.59955]
 [195.1895 ]
 [137.26027]]
950 cost 22.417505 
prediction
 [[157.44215]
 [179.66583]
 [185.57478]
 [195.19377]
 [137.27888]]
960 cost 22.249126 
prediction
 [[157.4251 ]
 [179.68466]
 [185.55016]
 [195.19803]
 [137.29747]]
970 cost 22.082073 
prediction
 [[157.4081 ]
 [179.70338]
 [185.52557]
 [195.20224]
 [137.31595]]
980 cost 21.916172 
pred

1710 cost 12.682989 
prediction
 [[156.30798]
 [180.90837]
 [183.95691]
 [195.46516]
 [138.51122]]
1720 cost 12.588966 
prediction
 [[156.29506]
 [180.92241]
 [183.93875]
 [195.4681 ]
 [138.52525]]
1730 cost 12.495623 
prediction
 [[156.28217]
 [180.93643]
 [183.92067]
 [195.47104]
 [138.5392 ]]
1740 cost 12.403017 
prediction
 [[156.26935]
 [180.95038]
 [183.90266]
 [195.47395]
 [138.55315]]
1750 cost 12.311088 
prediction
 [[156.25655]
 [180.96426]
 [183.88472]
 [195.47687]
 [138.56702]]
1760 cost 12.2199 
prediction
 [[156.24382]
 [180.97812]
 [183.86687]
 [195.47975]
 [138.58084]]
1770 cost 12.129437 
prediction
 [[156.23112]
 [180.9919 ]
 [183.84908]
 [195.48262]
 [138.59459]]
1780 cost 12.039607 
prediction
 [[156.21848]
 [181.00565]
 [183.83138]
 [195.48549]
 [138.60832]]
1790 cost 11.950496 
prediction
 [[156.20589]
 [181.01935]
 [183.81374]
 [195.48834]
 [138.62198]]
1800 cost 11.862012 
prediction
 [[156.19331]
 [181.03297]
 [183.79614]
 [195.49115]
 [138.63559]]
1810 cost 11