In [1]:
data = open('data-01-test-score.csv','w',encoding='utf8')
print('# EXAM1, EXAM2, EXAM3, FINAL\n73,80,75,152\n93,88,93,185\n88,91,90,180\n96,98,100,196\n73,66,70,142\n53,46,55,101', file= data)
data.close()

In [2]:
import numpy as np

In [3]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',',dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [4]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 88.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


*************************************************************

*************************************************************

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
tf.set_random_seed(777)

In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',',dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

* make sure the shape and data are ok

In [8]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 88.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


* placeholder for a tensor that will bw always fed

In [9]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [10]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

* Hypothisis

In [11]:
hypothesis = tf.matmul(X,W) + b

* Simplified cost/loss function

In [12]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

* mintimize

In [13]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

* Launch the graph in a session

In [14]:
sess = tf.Session()

* Initializes global variable in the graph

In [15]:
sess.run(tf.global_variables_initializer())

* Set up feeg_dict variables inside the loop

In [16]:
for step in range(2001):
    cost_val, hy_val,_=sess.run(
    [cost, hypothesis, train],
    feed_dict={X:x_data, Y:y_data})
    if step % 10 ==0:
        print(step, 'Cost', cost_val, '\nprediction\n', hy_val)

0 Cost 20386.096 
prediction
 [[22.048063 ]
 [21.619787 ]
 [23.29399  ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]
10 Cost 6.656916 
prediction
 [[155.22491]
 [181.74565]
 [180.4548 ]
 [194.08394]
 [140.77455]
 [ 97.31615]]
20 Cost 5.672014 
prediction
 [[156.12535]
 [182.84602]
 [181.52473]
 [195.25653]
 [141.61649]
 [ 97.94234]]
30 Cost 5.640638 
prediction
 [[156.12115]
 [182.85875]
 [181.52715]
 [195.26219]
 [141.6288 ]
 [ 97.95687]]
40 Cost 5.6094775 
prediction
 [[156.1108 ]
 [182.86401]
 [181.52226]
 [195.25989]
 [141.6354 ]
 [ 97.96721]]
50 Cost 5.57855 
prediction
 [[156.10045]
 [182.86922]
 [181.51733]
 [195.25757]
 [141.64197]
 [ 97.97747]]
60 Cost 5.547812 
prediction
 [[156.0901  ]
 [182.87437 ]
 [181.5124  ]
 [195.25523 ]
 [141.64848 ]
 [ 97.987686]]
70 Cost 5.5173078 
prediction
 [[156.07982]
 [182.87953]
 [181.50754]
 [195.2529 ]
 [141.655  ]
 [ 97.99789]]
80 Cost 5.4869876 
prediction
 [[156.06958 ]
 [182.8847  ]
 [181.50269 ]
 [195.25058 ]
 [141.66148 ]
 [ 98.008064]]

810 Cost 3.743371 
prediction
 [[155.40726 ]
 [183.21553 ]
 [181.18835 ]
 [195.10355 ]
 [142.07588 ]
 [ 98.666565]]
820 Cost 3.7248936 
prediction
 [[155.39925]
 [183.21948]
 [181.18454]
 [195.10178]
 [142.0808 ]
 [ 98.67454]]
830 Cost 3.7065494 
prediction
 [[155.39128]
 [183.22343]
 [181.18077]
 [195.10008]
 [142.08574]
 [ 98.68248]]
840 Cost 3.6883652 
prediction
 [[155.38338 ]
 [183.22739 ]
 [181.17703 ]
 [195.09834 ]
 [142.09064 ]
 [ 98.690414]]
850 Cost 3.6702547 
prediction
 [[155.37546]
 [183.23134]
 [181.1733 ]
 [195.09662]
 [142.09552]
 [ 98.6983 ]]
860 Cost 3.652296 
prediction
 [[155.3676  ]
 [183.23524 ]
 [181.16956 ]
 [195.09492 ]
 [142.10039 ]
 [ 98.706184]]
870 Cost 3.6344316 
prediction
 [[155.35973 ]
 [183.23915 ]
 [181.16583 ]
 [195.09323 ]
 [142.10522 ]
 [ 98.714005]]
880 Cost 3.616728 
prediction
 [[155.35191 ]
 [183.24303 ]
 [181.16212 ]
 [195.0915  ]
 [142.11006 ]
 [ 98.721825]]
890 Cost 3.5991018 
prediction
 [[155.34412 ]
 [183.24692 ]
 [181.15843 ]
 [195.08984

 [ 99.25337]]
1660 Cost 2.5407805 
prediction
 [[154.81607 ]
 [183.5081  ]
 [180.90839 ]
 [194.97841 ]
 [142.43614 ]
 [ 99.259415]]
1670 Cost 2.5302584 
prediction
 [[154.81007 ]
 [183.51106 ]
 [180.90556 ]
 [194.97717 ]
 [142.43974 ]
 [ 99.265495]]
1680 Cost 2.5198414 
prediction
 [[154.80411]
 [183.514  ]
 [180.90274]
 [194.97595]
 [142.44331]
 [ 99.2715 ]]
1690 Cost 2.5094693 
prediction
 [[154.79816]
 [183.51694]
 [180.89992]
 [194.97473]
 [142.44687]
 [ 99.27752]]
1700 Cost 2.499151 
prediction
 [[154.79219]
 [183.51985]
 [180.89711]
 [194.97351]
 [142.45042]
 [ 99.2835 ]]
1710 Cost 2.4889195 
prediction
 [[154.78629]
 [183.52275]
 [180.89432]
 [194.97234]
 [142.45398]
 [ 99.28948]]
1720 Cost 2.4787621 
prediction
 [[154.7804 ]
 [183.52563]
 [180.89153]
 [194.97113]
 [142.45747]
 [ 99.29543]]
1730 Cost 2.4686453 
prediction
 [[154.7745 ]
 [183.52855]
 [180.88876]
 [194.96992]
 [142.461  ]
 [ 99.30137]]
1740 Cost 2.4586165 
prediction
 [[154.76866 ]
 [183.53143 ]
 [180.88599 ]
 [19

* ask me score

In [17]:
print('Your score will be ', sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))

Your score will be  [[171.08965]]


In [18]:
print('other score will be ', sess.run(hypothesis, feed_dict={X:[[60,70,100],[90,100,80]]}))

other score will be  [[111.77626]
 [198.40393]]


*************************************************************

*************************************************************

In [34]:
import tensorflow as tf
tf.set_random_seed(777)

In [38]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

In [21]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

* default values, in case of empty columns. also specifies the type if the
* decoded result

In [22]:
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

* collect batches of csv in

In [23]:
train_x_batch, train_y_batch = \
tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

* placeholders for a tensor that will be always fed

In [24]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

* hypothesis

In [25]:
hypothesis = tf.matmul(X,W)+b

* simplified cost/ Loss function

In [26]:
cost = tf.reduce_mean(tf.square(hypothesis -Y))

* minimizer

In [27]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

* launch the graph in a session

In [28]:
sess = tf.Session()

* Intrializes global variable in the graph

In [29]:
sess.run(tf.global_variables_initializer())

* start populating filename queue

In [39]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.CancelledError'>, FIFOQueue '_7_batch/fifo_queue' is closed.
	 [[Node: batch/fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/packed, batch/packed_1)]]


In [42]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _= sess.run(
        [cost, hypothesis, train],
        feed_dict={X:x_batch, Y:y_batch})
    if step % 10 ==0:
        print(step, 'Cost: ', cost_val, '\nprediction:\n', hy_val)
        
coord.request_stop()
coord.join(threads)

OutOfRangeError: FIFOQueue '_15_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]

Caused by op 'batch_2', defined at:
  File "D:\anaconda\envs\chch4934\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\envs\chch4934\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\anaconda\envs\chch4934\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
  File "D:\anaconda\envs\chch4934\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "D:\anaconda\envs\chch4934\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "D:\anaconda\envs\chch4934\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-41-cd136a6db988>", line 20, in <module>
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\training\input.py", line 979, in batch
    name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\training\input.py", line 754, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 475, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 2764, in _queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_15_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]


In [41]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: # EXAM1
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", na_value="", use_quote_delim=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0)]]


OutOfRangeError: FIFOQueue '_15_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]

Caused by op 'batch_2', defined at:
  File "D:\anaconda\envs\chch4934\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda\envs\chch4934\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\anaconda\envs\chch4934\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
  File "D:\anaconda\envs\chch4934\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "D:\anaconda\envs\chch4934\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "D:\anaconda\envs\chch4934\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "D:\anaconda\envs\chch4934\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\anaconda\envs\chch4934\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "D:\anaconda\envs\chch4934\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-41-cd136a6db988>", line 20, in <module>
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\training\input.py", line 979, in batch
    name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\training\input.py", line 754, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 475, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 2764, in _queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "D:\anaconda\envs\chch4934\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_15_batch_2/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: batch_2 = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_2/fifo_queue, batch_2/n)]]
